# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.7.0
_src_path: gh:radio-aktywne/template-database-cockroach
accountname: radio-aktywne
databasename: sapphire
description: Broadcast shows data 🎭
docs: true
docsurl: https://radio-aktywne.github.io/sapphire
envprefix: SAPPHIRE
httpport: 10511
imagename: databases/sapphire
registry: true
releases: true
reponame: sapphire
repourl: https://github.com/radio-aktywne/sapphire
rpcport: 10512
sqlport: 10510
